/**
 * Ručně sestavený (curated) přehled aktuálně zlevněných kousků v "old money" stylu
 * dostupných v e-shopech, které doručují do ČR. Ceny a slevy u položek bez konkrétní
 * ceny se mění za chodu obchodu, proto karta vždy odkazuje přímo na živou
 * výprodejovou / kategorijní stránku obchodu, ne na konkrétní kus zboží, který
 * může být vyprodaný.
 *
 * snapshotDate = kdy byl tento přehled naposledy ručně ověřený.
 */
const SNAPSHOT_DATE = "2. 7. 2026";

const CATEGORIES = [
  { id: "saka", label: "Saka & obleky" },
  { id: "svetry", label: "Svetry & pleteniny" },
  { id: "kosile", label: "Košile" },
  { id: "kabaty", label: "Kabáty" },
  { id: "boty", label: "Boty" },
  { id: "doplnky", label: "Doplňky" },
];

let DEALS = [
  {
    store: "GANT.cz",
    title: "Saka a blejzry — sleva až 50 %",
    note: "Oficiální filtr rovnou zobrazuje aktuálně zlevněné kousky ze starších kolekcí. Doprava zdarma nad 1 999 Kč.",
    category: "saka",
    discount: 50,
    priceNote: "sleva až −50 %",
    url: "https://www.gant.cz/damska-saka-a-blazery-2/f/sleva-50",
    verified: true,
  },
  {
    store: "Massimo Dutti (přes Zalando)",
    title: "Blejzry v letním výprodeji — až −70 %",
    note: "Klasické jednořadové střihy, bavlna i viskózová směs — přesně ten uvolněný old money střih.",
    category: "saka",
    discount: 70,
    priceNote: "sleva až −70 %",
    url: "https://www.zalando.cz/damske-obleceni-bundy-kabatky-vyprodej/massimo-dutti/",
    verified: true,
  },
  {
    store: "Blažek",
    title: "Pánské obleky ve výprodeji",
    note: "Český krejčovský dům, obleky z italské vlny za zvýhodněné ceny — noblesní silueta na míru rozpočtu.",
    category: "saka",
    discount: null,
    priceNote: "výprodejové ceny",
    url: "https://www.blazek.cz/vyprodej-obleky/",
    verified: false,
  },
  {
    store: "Pietro Filipi",
    title: "Doprodej starších kolekcí — až −70 %",
    note: "Český výrobce klasického střihu, saka a kabáty. Souhrn aktuální nabídky napříč e-shopy.",
    category: "saka",
    discount: 70,
    priceNote: "sleva až −70 %",
    url: "https://www.modio.cz/pietro-filipi",
    verified: true,
  },
  {
    store: "Willsoor.cz",
    title: "Klíčové kousky pro old money styl",
    note: "Redakční výběr sak, vest a kalhot v tlumených barvách přímo od obchodu specializovaného na klasiku.",
    category: "saka",
    discount: null,
    priceNote: "dle aktuální nabídky",
    url: "https://www.willsoor.cz/blog/styl-old-money-jak-dosahnout-nenapadne-elegance-s-klicovymi-kousky-z-naseho-e-shopu/",
    verified: false,
  },
  {
    store: "Answear Lab",
    title: "Kašmírové a vlněné svetry",
    note: "Aktuálně od 919 Kč (původně 1 499–1 999 Kč) — tedy až −46 %.",
    category: "svetry",
    discount: 46,
    priceNote: "919–1 299 Kč, sleva až −46 %",
    url: "https://answear.cz/m/answear-lab/ona/obleceni/svetry",
    verified: true,
  },
  {
    store: "GANT Outlet (Zalando Lounge)",
    title: "Pleteniny, chinos a košile — až −59 %",
    note: "Členská výprodejová sekce (nutná bezplatná registrace do Lounge by Zalando).",
    category: "svetry",
    discount: 59,
    priceNote: "sleva až −59 %",
    url: "https://www.zalando-lounge.cz/gant-outlet/",
    verified: true,
  },
  {
    store: "Marks & Spencer",
    title: "Kašmírové svetry — sekce Price Drop",
    note: "Sledujte stránku se snižovanými cenami a outlet na Zalando Lounge — kašmír je jejich stálice.",
    category: "svetry",
    discount: null,
    priceNote: "dle aktuální nabídky",
    url: "https://marksandspencerstore.cz/en/prices-drop",
    verified: false,
  },
  {
    store: "Tommy Hilfiger (přes Footshop)",
    title: "Pletené svetry se znakovou vlaječkou — až −70 %",
    note: "Klasické crew-neck a cable-knit svetry, ikonická trikolóra na rukávu.",
    category: "svetry",
    discount: 70,
    priceNote: "sleva až −70 %",
    url: "https://www.footshop.com/en/1118-sweaters/brand-tommy_hilfiger",
    verified: true,
  },
  {
    store: "GLAMI.cz",
    title: "Zlevněné pánské košile — přes 6 000 kousků",
    note: "Agregátor napříč obchody — filtrujte na „oxford“ pro typický knoflíčkový límeček.",
    category: "kosile",
    discount: null,
    priceNote: "dle vybraného obchodu",
    url: "https://www.glami.cz/panske-kosile/vyprodej/",
    verified: false,
  },
  {
    store: "TheyWear.cz",
    title: "Výprodej pánských košil",
    note: "Klasické střihy v jednobarevném provedení i jemném proužku.",
    category: "kosile",
    discount: null,
    priceNote: "výprodejové ceny",
    url: "https://www.theywear.cz/vyprodej-panske-kosile",
    verified: false,
  },
  {
    store: "s.Oliver",
    title: "Výprodej — pánské košile",
    note: "Sezónní výprodejová sekce s klasickými i neformálnějšími střihy.",
    category: "kosile",
    discount: null,
    priceNote: "výprodejové ceny",
    url: "https://www.soliver.cz/c/panove/vyprodej/kosile/",
    verified: false,
  },
  {
    store: "Zalando",
    title: "Dámské vlněné kabáty ve výprodeji",
    note: "Filtrujte barvu na „camel“ / „beige“ — přesně ten klasický velbloudí kabát.",
    category: "kabaty",
    discount: null,
    priceNote: "výprodejové ceny",
    url: "https://www.zalando.cz/damske-obleceni-vlnene-kabaty-vyprodej/",
    verified: false,
  },
  {
    store: "C&A",
    title: "Kolekce „Old Money“",
    note: "Obchod má rovnou vlastní kategorii pojmenovanou Old Money — tlumené tóny, nadčasový střih.",
    category: "kabaty",
    discount: null,
    priceNote: "dle aktuální nabídky",
    url: "https://www.c-and-a.com/eu/cz/shop/trendove-kategorie-old-money",
    verified: false,
  },
  {
    store: "Baťa",
    title: "Semišové penny loafers se sponou",
    note: "Aktuálně 999 Kč (z 1 999 Kč) — sleva −50 %.",
    category: "boty",
    discount: 50,
    priceNote: "999 Kč (z 1 999 Kč)",
    url: "https://www.bata.com/cz/zeny/obuv/mokasiny/",
    verified: true,
  },
  {
    store: "Wojas.cz",
    title: "Kožené penny loafers",
    note: "Hnědé kožené mokasíny 1 799 Kč (z 2 899 Kč) — sleva −38 %.",
    category: "boty",
    discount: 38,
    priceNote: "1 799 Kč (z 2 899 Kč)",
    url: "https://wojas.cz/hnede-kozene-damske-mokasiny-typu-penny-loafers-46354-52",
    verified: true,
  },
  {
    store: "Gentleman Store",
    title: "Mokasíny a bostonky",
    note: "Český obchod specializovaný na pánský old money šatník — pečlivě vybíraná klasika.",
    category: "boty",
    discount: null,
    priceNote: "dle aktuální nabídky",
    url: "https://www.gentlemanstore.cz/boty/boty-139/mokasiny/",
    verified: false,
  },
  {
    store: "SmartMen.cz",
    title: "Hedvábné kravaty a motýlky",
    note: "Útlý (slim) i klasický střih, jednobarevné i vzorované varianty.",
    category: "doplnky",
    discount: null,
    priceNote: "dle aktuální nabídky",
    url: "https://www.smartmen.cz/muzi/doplnky/kravaty-motylky",
    verified: false,
  },
  {
    store: "Modio.cz",
    title: "Hedvábné šátky — 187 kousků",
    note: "Agregátor napříč obchody, značky jako GANT, Karl Lagerfeld či Missoni.",
    category: "doplnky",
    discount: null,
    priceNote: "dle vybraného obchodu",
    url: "https://www.modio.cz/t/hedvabne-satky",
    verified: false,
  },
];
